FixedDD/Controllers/AirLinesNamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FixedDD.Models;

namespace WebApplication2.Controllers
{
    public class AirLinesNamesController : Controller
    {
        private myAmdDB db = new myAmdDB();

        public ActionResult Index(int? page, string search)
        {
            IQueryable<AirLinesName> stdList;
            int totalskip;
            GetIndex(page, search, out stdList, out totalskip);
            return View(stdList.Skip(totalskip).Take(20));
        }
        public PartialViewResult NextPage(int? page, string search)
        {
            IQueryable<AirLinesName> stdList;
            int totalskip;
            GetIndex(page, search, out stdList, out totalskip);
            return PartialView(stdList.Skip(totalskip).Take(20));
        }
        private void GetIndex(int? page, string search, out IQueryable<AirLinesName> stdList, out int totalskip)
        {
            int pageno = page ?? 1;
            totalskip = (pageno - 1) * 20;
            if (string.IsNullOrEmpty(search))
                stdList = db.AirLinesName.OrderBy(b => b.id);
            else
                stdList = db.AirLinesName.Where(b => b.AL_Code.Contains(search)).OrderBy(b => b.id);
            ViewBag.totalrecord = stdList.Count();
        }
        // GET: AirLinesNames/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AirLinesName airLinesName = db.AirLinesName.Find(id);
            if (airLinesName == null)
            {
                return HttpNotFound();
            }
            return View(airLinesName);
        }

        // GET: AirLinesNames/Create
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public JsonResult GetAirLinesName(string Prefix)
        {

            var GetAirLinesName = (from c in db.AirLinesName
                               where c.AL_Name.StartsWith(Prefix) || c.AL_Code.StartsWith(Prefix)
                               select new
                               {
                                   c.AL_Name,
                                   c.AL_Code,                                 

                               }).ToList();



            if (GetAirLinesName != null)
            {
                //  var BindInf = GetCityData.
            }


            return Json(GetAirLinesName, JsonRequestBehavior.AllowGet);
        }
        // POST: AirLinesNames/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,AL_Code,AL_Name,CreatedDate")] AirLinesName airLinesName)
        {
            if (ModelState.IsValid)
            {
                db.AirLinesName.Add(airLinesName);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(airLinesName);
        }

        // GET: AirLinesNames/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AirLinesName airLinesName = db.AirLinesName.Find(id);
            if (airLinesName == null)
            {
                return HttpNotFound();
            }
            return View(airLinesName);
        }

        // POST: AirLinesNames/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,AL_Code,AL_Name,CreatedDate")] AirLinesName airLinesName)
        {
            if (ModelState.IsValid)
            {
                db.Entry(airLinesName).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(airLinesName);
        }

        // GET: AirLinesNames/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AirLinesName airLinesName = db.AirLinesName.Find(id);
            if (airLinesName == null)
            {
                return HttpNotFound();
            }
            return View(airLinesName);
        }

        // POST: AirLinesNames/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AirLinesName airLinesName = db.AirLinesName.Find(id);
            db.AirLinesName.Remove(airLinesName);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FixedDD/Controllers/CityListsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FixedDD.Models;

namespace FixedDD.Controllers
{
    public class CityListsController : Controller
    {
        private myAmdDB db = new myAmdDB();

        // GET: CityLists
        public ActionResult Index(int? page, string search)
        {
            IQueryable<CityList> stdList;
            int totalskip;
            GetIndex(page, search, out stdList, out totalskip);
            return View(stdList.Skip(totalskip).Take(20));
        }
        public PartialViewResult NextIndex(int? page, string search)
        {
            IQueryable<CityList> stdList;
            int totalskip;
            GetIndex(page, search, out stdList, out totalskip);
            return PartialView(stdList.Skip(totalskip).Take(20));
        }
        private void GetIndex(int? page, string search, out IQueryable<CityList> stdList, out int totalskip)
        {
            int pageno = page ?? 1;
            totalskip = (pageno - 1) * 20;
            if (string.IsNullOrEmpty(search))
                stdList = db.CityList.OrderBy(b => b.id);
            else
                stdList = db.CityList.Where(b => b.AirportCode.Contains(search)).OrderBy(b => b.id);
            ViewBag.totalrecord = stdList.Count();
        }
        // GET: CityLists/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CityList cityList = db.CityList.Find(id);
            if (cityList == null)
            {
                return HttpNotFound();
            }
            return View(cityList);
        }

        // GET: CityLists/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CityLists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,AirportCode,AirportName,CityName,CountryName,CountryCode,Latitude,Longitude,WorldAreaCode,Counter,orderseq")] CityList cityList)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.CityList.Add(cityList);
                    db.SaveChanges();
                    TempData["Msg"] = 1;
                }
            }
            catch (Exception ex)
            {
                if (ex.ToString().Contains("Duplicate_Id"))
                    TempData["Msg"] = 0;
            }
            return RedirectToAction("Index");
        }

        // GET: CityLists/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CityList cityList = db.CityList.Find(id);
            if (cityList == null)
            {
                return HttpNotFound();
            }
            return View(cityList);
        }

        // POST: CityLists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,AirportCode,AirportName,CityName,CountryName,CountryCode,Latitude,Longitude,WorldAreaCode,Counter,orderseq")] CityList cityList)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cityList).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cityList);
        }

        // GET: CityLists/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CityList cityList = db.CityList.Find(id);
            if (cityList == null)
            {
                return HttpNotFound();
            }
            return View(cityList);
        }

        // POST: CityLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CityList cityList = db.CityList.Find(id);
            db.CityList.Remove(cityList);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FixedDD/Views/Shared/Popup.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/images/favicon.ico">
    <script src="~/AdminCssJS/JS/jquery-2.2.0.min.js"></script>
    <link href="~/AdminCssJS/CSS/font-awesome.min.css" rel="stylesheet" />
    <link href="~/AdminCssJS/bootstrap.min.css" rel="stylesheet" />
    <link href="~/AdminCssJS/CSS/bootstrap-switch.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-table.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap-table.js"></script>
</head>
<body>

    <div class="page-content">
        <div>
            @RenderBody()
        </div>
    </div>    
    @* Core Level Plugins *@
    <script src="~/AdminCssJS/bootstrap.min.js"></script>
    <script src="~/AdminCssJS/JS/bootstrap-switch.min.js"></script> 
    <script src="~/AdminCssJS/JS/bootstrap-table.js"></script>    
</body>
</html>

FixedDD/Views/Shared/SeeingoMaster.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/images/favicon.ico">
    <script src="~/AdminCssJS/JS/jquery-2.2.0.min.js"></script>
    <link href="~/AdminCssJS/CSS/font-awesome.min.css" rel="stylesheet" />
    <link href="~/AdminCssJS/CSS/simple-line-icons.min.css" rel="stylesheet" />
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@
    <link href="~/AdminCssJS/bootstrap.min.css" rel="stylesheet" />
    <link href="~/AdminCssJS/CSS/bootstrap-switch.min.css" rel="stylesheet" />
    <link href="~/AdminCssJS/CSS/morris.css" rel="stylesheet" />
    <link href="~/AdminCssJS/CSS/components.min.css" rel="stylesheet" />
    <link href="~/AdminCssJS/CSS/plugins.min.css" rel="stylesheet" />
    <link href="~/AdminCssJS/CSS/layout.min.css" rel="stylesheet" />
    <link href="~/AdminCssJS/CSS/darkblue.min.css" rel="stylesheet" />
    <link href="~/Content/SPG.css" rel="stylesheet" />
    @* Page Level Plugins *@
    <link href="~/Content/bootstrap-table.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap-table.js"></script>
    <style>
        ::-webkit-scrollbar {
            width: 8px;
            height: 5px;
        }

        ::-webkit-scrollbar-track {
            background-color: #fff;
            border-left: 1px solid #ccc;
        }

        ::-webkit-scrollbar-thumb {
            background-color: #8ecf52;
        }

            ::-webkit-scrollbar-thumb:hover {
                background-color: #8ecf52;
            }
            .page-header.navbar{background-color:#fff!important;box-shadow: 0 0 5px rgb(0 0 0 / 30%);color: #000 !important;}
    </style>
    <script type="text/javascript">
        var UrlBase = "/";// location.protocol + '//' + location.host + '/fixedDeparture/'
        if (@Session["isExecutive"].ToString()!= "1") {
            UrlBase = location.protocol + '//' + location.host + '/fixedDeparture/';
        }
        //var UrlBase = 'http://localhost:56359/';
        //var ApplUrl = 'http://b2b.//.com/';
    </script>
</head>
<body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white">
    <div class="page-wrapper">
        BEGIN HEADER
        <div class="page-header navbar navbar-fixed-top">
            <!-- BEGIN HEADER INNER -->
            <div class="page-header-inner ">
                <!-- BEGIN LOGO -->
                <div class="page-logo">
                    <a href="#">
                        @*<h3 class="logo-default" style="font-size: 28px;color:#ffffff; margin-top: 9px;">Tripforo</h3>*@
                        <img class="logo-default" src="~/images/logo(ft).png" style="width: 158px;margin-top: 6px;" />
                    </a>
                    <div class="menu-toggler sidebar-toggler">
                        <span></span>
                    </div>
                </div>
                <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
                    <span></span>
                </a>





                <div class="top-menu">
                    <ul class="nav navbar-nav pull-right">
                        <li class="dropdown dropdown-user" style="padding: 11px;">
                            <b  title="name">
                                <b class="belStyle shakedsreportval" style="font-size: 16px!important;"> <span class="fa fa-user-secret"></span> <span id="agentname"></span> </b>
                            </b>
                        </li>
                        <li class="dropdown dropdown-user" style="padding: 11px;">
                            <b title="Balance">
                                <b class="belStyle shakedsreportval" style="font-size: 16px!important;">Balance : <span class="fa fa-inr"></span> <span id="supbalance"></span> </b>
                            </b>
                        </li>

                        <li class="dropdown dropdown-user">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" style="background: #7a8b9f;color: #fff!important;">
                                <img src="~/images/admin.png" alt="" class="img-circle" />
                                <span class="username username-hide-on-mobile" style="color: #fff!important;">My Profile </span>
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-default">
                                <li class="">
                                    <a href="#">
                                        <i class="icon-user"></i> My Profile
                                    </a>
                                </li>

                                <li class="divider"> </li>
                                <li>
                                    @if (Session["isExecutive"] != null)
                                    {
                                        <a href="/FlightSearchResults/Logout">
                                            <i class="icon-key"></i> Log Out
                                        </a>
                                    }
                                    else
                                    {
                                        <a href="/FixedDeparture/FlightSearchResults/Logout">
                                            <i class="icon-key"></i> Log Out
                                        </a>
                                    }

                                </li>
                            </ul>
                        </li>


                        <li class="dropdown dropdown-quick-sidebar-toggler">
                            @{
                                var stringurl = "";
                                if (Session["isExecutive"].ToString() == "1")
                                {
                                    stringurl = "/FlightSearchResults";
                                }
                                else
                                {
                                    stringurl = "/FixedDeparture/FlightSearchResults";
                                }
                                <a href="@stringurl/Logout" class="dropdown-toggle">
                                    <i class="icon-logout"></i>
                                </a>
                            }
                        </li>

                        @if (Session["isExecutive"].ToString() != "1")
                        {
                            <li class="dropdown dropdown-quick-sidebar-toggler">
                                <input id="LoginButton" type="button" class="btn btn-success btn-lg" value="Back To Support" onclick="backHome()" />
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
        <div class="clearfix"> </div>
        <div class="page-container">
            <div class="page-sidebar-wrapper">
                <div class="page-sidebar navbar-collapse collapse">
                    <ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
                        <li class="sidebar-toggler-wrapper hide">
                            <div class="sidebar-toggler">
                                <span></span>
                            </div>
                        </li>

                        <li class="nav-item start active open">
                            <a href="" class="nav-link nav-toggle">
                                <i class="icon-home"></i>
                                <span class="title">Dashbord</span>
                                <span class="selected"></span>
                            </a>
                        </li>

                        <li class="heading">
                            <h3 class="uppercase">Features</h3>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("TicketReport","FlightSearchResults")" class="nav-link nav-toggle">
                                <i class="glyphicon glyphicon-check"></i>
                                <span class="title">Booking Report</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("LedgerReport","FlightSearchResults")" class="nav-link nav-toggle">
                                <i class="glyphicon glyphicon-check"></i>
                                <span class="title">Ledger Report</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("HoldPnrRequest","FlightSearchResults")" class="nav-link nav-toggle">
                                <i class="glyphicon glyphicon-check"></i>
                                <span class="title">Hold Pnr Request</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","FlightSearchResults")" class="nav-link nav-toggle">
                                <i class="glyphicon glyphicon-plane"></i>
                                <span class="title">Flight Search</span>
                            </a>
                        </li>
                        @*<li class="nav-item">
                            <a href="@Url.Action("Sector","FlightSearchResults")" class="nav-link nav-toggle">
                                <i class="glyphicon glyphicon-download"></i>
                                <span class="title">Sector Wise Flight</span>
                            </a>
                        </li>*@
                        @if (Session["isExecutive"] == null)
                        {

                            <li class="nav-item">
                                <a href="@Url.Action("Index","CityLists")" class="nav-link nav-toggle">
                                    <i class="glyphicon glyphicon-apple"></i>
                                    <span class="title">City List</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Index","AirLinesNames")" class="nav-link nav-toggle">
                                    <i class="glyphicon glyphicon-bell"></i>
                                    <span class="title">AirLines Names</span>
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>

            <div class="page-content-wrapper">
                <div class="page-content">
                    <div>
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
    @* Core Level Plugins *@
    <script src="~/AdminCssJS/bootstrap.min.js"></script>
    <script src="~/AdminCssJS/JS/bootstrap-switch.min.js"></script>
    <script src="~/AdminCssJS/JS/morris.min.js"></script>
    <script src="~/AdminCssJS/JS/moment.min.js"></script>
    <script src="~/AdminCssJS/JS/app.min.js"></script>
    <script src="~/AdminCssJS/JS/dashboard.min.js"></script>
    <script src="~/AdminCssJS/JS/layout.min.js"></script>
    @* Page Level Plugins *@

    <script src="~/AdminCssJS/JS/bootstrap-table.js"></script>
    <script src="~/AdminCssJS/JS/bootstrap-table-export.js"></script>
    <script src="~/AdminCssJS/JS/tableExport.js"></script>

    <link href="~/Content/summernote.css" rel="stylesheet" />
    <script src="~/Content/summernote.js"></script>
    <script>
        $('.summernote').summernote({
            height: 400
        });

        $('.summernote1').summernote({
            height: 300
        });



        function backHome() {
            debugger;
            $.ajax({
                url: "FlightSearchResults/Backhome",
                // data: "{ 'Mobile': '" + MobileNo + "','Email': '" + Email + "' }",
                dataType: "json", type: "POST",
                contentType: "application/json; charset=utf-8",

                success: function (response) {
                    debugger;

                    window.location = response;


                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    debugger;
                    alert(textStatus);

                }
            });




        }




    </script>
    <script>
        $.ajax({
            url: "/FlightSearchResults/Getsuppliorbalance",
            type: "POST",
            dataType: "json",
            success: function (data) {
                if (data.length > 0) {
                    $("#agentname").html(data[0]);
                    $("#supbalance").html(data[1]);
                }

            }
        })
    </script>

</body>
</html>